services:
  - type: web
    name: NEPTUNE-V3
    env: node
    branch: main
    repo: https://github.com/macksyn/Izumi-v3.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
